# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         mybench
version:      1.0
version_from: MyBench.pm
installdirs:  site
requires:
    DBD::mysql:                    1
    DBI:                           1.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
